insert into faction (idF, nom, appartenance, influence, age, bio) values 
(1, "L'Imperium de l'humanité", NULL, "Omniprésents dans la galaxie", "douze mille ans", "L'imperium de l'humanité est une race relativement jeune à l'échelle de la galaxie, mais elle en est actuellement la dominante. Basé aujourd'hui sur un système autoritaire et militariste, L'imperium, belliqueux, refuse tout contact avec d'autres races et livre une guerre éternelle et acharnée contre toutes les races xenos de la galaxie, et son plus grand ennemi, Le Chaos."),
(2, "Le Chaos", NULL, "Absolue dans le warp, omniprésents dans la galaxie", "génèse", "Le Chaos ou Warp est la dimension immatérielle qui se superpose à la nôtre dans l'univers. Celle-ci abrite toutes les créatures démoniaques de la galaxie, incapables de mourir. Il est directement nourri par les êtres vivants du monde matériel par leurs passions et impulsions. Son but est la croissance infinie de son influence et de ses disciples. Il existe depuis aussi longtemps que la vie consciente existe."),
(3, "Empire T'au", NULL, "modérée voir insignifiante", "environ deux mille ans", "Les T'au sont la race la plus jeune de la galaxie. Leur empire est encore petit et peu influent, mais ils se sont développés particulièrement rapidement et font partie des races à la technologie la plus évoluée de la galaxie. Leur insignifiance est à la fois leur bénédiction car elle leur a permis de ne pas se faire éradiquer par l'Imperium, quand bien d'autres menaces plus importantes se présentent. Les T'au agissent au nom du bien suprême, et la plupart de leurs citoyens sont à la botte de la caste dirigeante qui leur ment sur la grandeur de leur empire."),
(4, "Aeldari", "Les Anciens", "Forte dans toute la galaxie", "plus de 60 millions d'années", "Les Aeldari font partie des races les plus anciennes de la galaxie. Créés par les Anciens et utilisés dans la guerre céleste opposant les Anciens et les Nécrons, cette race à l'origine extrêmement belliqueuse en est venue à reigner sur la galaxie pendant 60 millions d'années. Il y a 40 000 ans de cela, à force d'orgies et d'excès, les Aeldari ont créé le quatrième des 4 dieux du chaos : Slaanesh, le dieu de l'excès. Cette évènement appelé La Chute a détruit les Aeldari, et aujourd'hui ils ne sont plus que l'ombre de leur passé, séparés et au bord de l'extinction."),
(5, "Nécrons", "Nécrontyrs", "Moyenne dans toute la galaxie", "environ 70 millions d'années", "Les Nécrons sont actuellement la race de la galaxie la plus ancienne. Ils se sont battus contre les Anciens les Aeldari les Orks et les K'tan pendant les guerres célestes, puis leur leader, le roi Silencieux a plongé le peuple dans un sommeil de 60 millions d'années. Cette race est issue des Nécrontyrs, un peuple souffrant issu d'une planète extrêmement hostile. A l'issu de la rencontre des nécrontyrs et des K'tan, ceux-ci firent le pacte de l'immortalité, et perdirent leur chair pour devenir les automates dénués de volonté qu'ils sont aujourd'hui. Rares sont les nécrons à qui il reste encore un semblant de conscience. Ce peuple lobotomisé se bat à ce jour pour la protection de ses mondes cryptes et contre la prolifération du Chaos dans la galaxie."),
(6, "Tyranids", NULL, "Omniprésents dans la galaxie", "deux mille ans dans notre galaxie, origine inconnue", "Les Tyranids, aussi appelé le Grand Dévoreur est une race extraterrestre extrêmement dangereuse. Ils viendraient d'une autre galaxie, qu'ils auraient éradiqué en l'engloutissant en entier. Leur insatiable appétit ne s'ârrete à rien, et ils ont effectué leur voyage à travers le vide intersidéral dans l'unique but de se nourrir. Ils sont séparés en plusieurs flottes-ruches, présentes à différents endroits de notre galaxie, et sont un ennemi extrêmement dangereux pour chaque race habitant notre galaxie, L'Imperium y compris. Les tyranids obéissent à une conscience collective qui est poussée par leurs esprits les plus puissant, donc le régent est l'Esprit-Ruche."),
(7, "Orcs", "Les Anciens", "Forte dans toute la galaxie", "plus de 60 millions d'années", "Les Anciens sont une race disparue de nôtre galaxie. La plus ancienne de toutes, ils étaient pacifistes et ont donné la vie à la majorité des autres races extraterrestes, commes les Aeldari et les Orks. Ils ont établi contact avec les Nécrontyrs il y a de cela plus de 60 millions d'années, mais, refusant de leur offrir l'immortalité que ces derniers voulaient, ils déclenchèrent une guerre dévastatrice qui réveilla jusqu'aux premières puissances primordiales de la Ruine. Au terme de cette guerre, Les Anciens disparurent, tués par les Nécrontyrs et il ne reste aujourd'hui plus rien de leur passage pourtant important dans notre galaxie, si ce n'est leurs création.");

insert into personnage (nom, idF, sousFaction, age, taille, genre, statut, classe, bio) values
("L'Empereur de l'humanité", 1, NULL, "environ 40 mille ans", "4,20 mètres", "homme", "Légume", "Divin", "L'empereur de l'humanité est un des premiers perpétuels. Pendant des milliers d'années, grâce à ses pouvoirs psychiques de vision extrêmement puissants, lui et un groupe de perpertuels qui le suivait, opéraient dans le but d'un jour guider l'humanité vers un avenir plus sain. Il conduisit les guerres de réunification de Terra et réunit les peuples humains sous une seule bannière, celle de l'Imperium de l'Humanité. Il est également à l'origine de la conception artificielle de ses fils, les Primarches, tous des demi-dieux, et de leurs enfants, les Space Marines. Aujourd'hui la volonté de l'Empereur continue encore de guider l'Imperium tout entier, bien que sa carcasse gît sur son trône d'or, presque sans vie."),
("Horus Lupercal", 2, "Sons of Horus", "environ 5 mille ans", "3,20 mètres", "homme", "Décédé", "Divin", "Horus est le Primarche des Sons of Horus, la XVIe légion de Space Marines de l'Empereur. Nommé maître de guerre par ce dernier, il était considéré comme le préféré du maître de l'humanité. Mais avec 8 de ses frères, Horus, face aux mensonges que lui avait caché son père et une rage envers sa manie de cacher tous ses plans et toutes leurs conséquences désastreuses sur la Galaxie à tout le monde, fomenta une rébellion. La plus grande Jamais vécue par L'Imperium : L'Hérésie d'Horus. Celle-ci Manqua de peu de briser l'Imperium pour de bon et de faire définitivement triompher le Chaos dans l'équilibre des forces de la galaxie. Au terme de cette Rébellion, Horus mouru de la main de l'Empereur, mais il infligea à ce dernier une blessure si grave qu'il n'est pas dit que l'Empereur puisse s'en remettre un jour."),
("Eldrad Ulthran", 4, "Vaisseau Monde Ulthwé", "plus de 12 mille ans", "1,80 mètres", "homme", "Revenu à la vie", "Psychiquement surpuissant", "Eldrad Ulthran est un Prescient Aeldari du vaisseau-monde Ulthwé. Celui-ci déjà spécialisé dans les arts psychiques, Eldrad est le plus puissant de son espece. Il est agé de plus de 10 000 ans et était déjà connu à l'ère de l'Hérésie d'Horus. Il se démarque beaucoup de ses compères Aeldari par son amour pour l'être humain. Au cours de sa longue vie, Eldrad a eu l'opportunité d'entrer en contact avec moult civilisations, et il fut prit d'affection pour les humains, qui se battaient inlassablement au péril de leur vie contre les forces du Chaos. Pour ces raisons, il fut expulsé de son vaisseau-monde, qui lui, croyait fermement que c'est l'extermination de la race humaine qui apporterait l'équilibre dans la galaxie. Il vadrouille aujourd'hui au côté des dévôts d'Ynnead dans le but de ramener le disparu Dieu des Murmures, dans l'espoir de libérer les Aeldari de leurs souffrances éternelles."),

insert into planete (nom, statut, idF, bio) values
("Cadia", "Anéantie", 1, "Cadia est une des planètes les plus importantes de l'Imperium, peut-être même une des plus importantes de la galaxie. Cadia est un monde militaire occupé par L'Imperium de l'humanité, dont est originaire le très fameux corps d'armée Cadien. Sur cette planète se trouvait un pylone d'annulation psychique déposé là par les Nécrons il y a de cela des dizaines de millions d'années. Ce pylone permettait de garder une frontière nette entre l'univers matériel et le warp. Mais suite à un assaut dirigé par Abbadon, Cadia tomba, et le pylone détruit, une gigantesque faille Warp appelée Cicatrix Maledictum déchira la galaxie en deux, perturbant toutes les races qui y vivaient et les exposant directement à des incursions du Warp. CADIA TIENDRA !"),
("Terra", "Active", 1, "C'est Terra, le monde d'origine de L'Imperium de l'Humanité quoi. Y a tout dessus.")

insert into minifigs_sets (nom, prix, stock, idF) values
("escouade d'intercesseurs", 51.25, 1, 1),
("Lances Etincelantes", 55.00, 10, 4),
("Le Visarque", 26.00, 0, 4),
("Corps de Titan Phantom", 625.00, 1, 4);